### ISSUE TITLE
Verify local build on main

### ISSUE THREAD

**Issue by michaelhaaf** [kbaggott1/FitFolio#133]
---
title: Verify local build on main
milestone: Milestone 4b Requirements
label: bug
---

## Requirement
The latest version of your `main` branch should build when pulled on to a developer's machine (i.e. not just "work for mysterious reasons" on an emulator). Your code and your gradle configurations should be able to reliably build your project code on the `main` branch.

## To Reproduce/Verify
To reproduce locally:
1. Pull the latest version of your `main` branch on to your developer machine
1. Open in project in Android Studio
2. Open the terminal within Android Studio
3. Run `./gradlew build` (press CTRL+ENTER to let Android Studio manage your PATH/gradle environment)

If you have a working GitHub action that builds the project, you can navigate to Actions to see the result of the latest build.

## Expected behavior
BUILD SUCCEEDED

## To Fix
If your build does not succeed on main, you need to diagnose the reason why, make the necessary code changes, then complete a pull request into `main` that fixes the issues.

## Before completing this ticket:

- [x] your latest `main` branch code builds locally following the steps above
- [x] (if necessary) changes needed to fix build so it does pass have been pulled onto the `main` branch of your repository

**Comment by Cristiano-Fazi** [comment]
Project main branch builds
