### ISSUE TITLE
Implement advanced feature(s)

### ISSUE THREAD

**Issue by michaelhaaf** [kbaggott1/FitFolio#145]
---
title: Implement advanced feature(s)
milestone: Milestone 4b Requirements
label: enhancement
---

## Requirements

One of the technical requirements defined for this project way at the beginning of the semester was to implement an "advanced feature" not covered in class. 

This ticket will track any advanced features that you implement. **Link the PRs/Issues you have created for any "advanced features" to this issue**. Close the issue when you have added all the "advanced features" you plan to implement.

## Priority
You can leave this task for last, but make sure it is done before the deadline.

## Resources (i.e. what is considered "advanced")

All of the below are optional. You should complete at least one; but you should also try to do more than one if you have time for full marks (I've tried to put examples that are interesting!)

You may also choose to do something outside of what I've provided here -- just link the PR to this issue and explain if necessary how it is "advanced"/beyond what we've learned.

- As said in class: Firestore for remote storage.
- Use Hilt for dependency injection
- Find a codelab on [codelabs.developers.google.com](https://codelabs.developers.google.com/) (one for Android using Jetpack Compose) and see if you can apply what you've learned to your app. I've picked a few examples (in order from top to bottom of most relevant/realistic to hardest/technical but mabye cool)
    - [Beautiful Transitions with Material3](https://developer.android.com/codelabs/material-motion-android?hl=en#0)
    - [Using Hilt for Dependency Injection (good design pattern/code quality improvment)](https://developer.android.com/codelabs/android-hilt?hl=en#0)
    - [Android Paging for optimizing app performance/speed](https://developer.android.com/codelabs/android-paging?hl=en#0)
    
- (small on its own, but a good top up) Automated badges in README

## Before completing this ticket:**

- [ ] Any advanced features above that you have finished should be linked to this issue (their pull request)

**Comment by Cristiano-Fazi** [comment]
We have already implemented Firestore
