### ISSUE TITLE
Ensure app accessility/usability

### ISSUE THREAD

**Issue by michaelhaaf** [kbaggott1/FitFolio#149]
---
title: Ensure app accessility/usability
milestone: Milestone 4b Requirements
label: enhancement
---

## Requirements
- A core requirement is for your app to be usable. You should actually try using your app on a mobile phone and keeping track of any improvements you make to the usability (device rotation, typing, clicking buttons, navigating, etc.)
- You should use the techniques learned in Assignment 4 and ensure your entire app adheres to basic accesibility standards (color contrast, button size, semantics, etc.)

## Priority
You can leave this task for last, but make sure it is done before the deadline.

## Resources

- See Assignment 4 codelab
- You will have to do some independent research to solve the usability problems you may encounter in your application. Remember that the course notes have a lot of resources to start with especialyl re: state management/UI/etc.

## Before completing this ticket:**

- [ ] Entire codebase has been gone over for these kind of issues/improvements
- [ ] All usability improvements you make are linked/documented here

**Comment by Cristiano-Fazi** [comment]
App is already accessible
