### ISSUE TITLE
Material Design Refactor/Improvement

### ISSUE THREAD

**Issue by michaelhaaf** [kbaggott1/FitFolio#150]
---
title: Material Design Refactor/Improvement
milestone: Milestone 4b Requirements
label: enhancement
---

## Requirements
This ticket tracks any changes you make to improve the theme/cohesion/design of your app. I'm leaving this open ended: make use of the Material3 course notes and android developer docs to apply best practises (in code and design).

## Priority
You can leave this task for last, but make sure it is done before the deadline.

## Resources

- See course notes
- See Material3 codelabs/android developer documentation
- For creating/using assets (images, backgrounds, etc): Look up "open-source" "Android" "assets" and try to find svgs. You can also try your hand at free/open source programs like Inkscape if you like.
- Open ended research: I'm sure you can find some great youtube tutorials/etc out there on this kind of thing. Sorry, I've run out of time to make more concrete reqs.

## Before completing this ticket:**

- [x] #116 Redo About Page UI
- [x] #115 Redo Motivation Page UI

**Comment by Cristiano-Fazi** [comment]
All UI is updated and pretty.
