### ISSUE TITLE
Motivational Quote of the Day in "Motivation" Page

### ISSUE THREAD

**Issue by kbaggott1** [kbaggott1/FitFolio#71]
**Task Description**
An API call will be made in order to retrieve a motivational quote each day

**Steps**

- Find API that contains motivational quotes
- Make API call each day for a new motivational quote to go into "Motivation" Page

**Technical effort (LOE)**
Breakdown the set of steps that need by level of effort (LOE) estimates.

**Comment by Cristiano-Fazi** [comment]
This was cut
