### ISSUE TITLE
Create Exercises Repository Interface

### ISSUE THREAD

**Issue by Cristiano-Fazi** [kbaggott1/FitFolio#93]
**Task Description**
Create the interface that the repository will interact with when retrieving the exercises data from the database.

**Steps**

- Create the interface
- Add the methods that will be used to access the data

**Comment by kbaggott1** [comment]
We realized that this is not necessary for the goal of our project

**Comment by kbaggott1** [comment]
We realized that this is not necessary for the goal of our project
